name: TMNF
favicon: null
layout_spectrum: 0.9735
typography_spectrum: 0
title: Teenage Mutant Ninja December
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#442218'
    - '#958578'
    - '#5f4f3f'
    - '#c1b9a6'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
